### PR TITLE
7 renaming Cyberkit4SME groups and paths to state_report_management

### LINKED ISSUE #7: Tidy up API documentation
There is a group of API endpoints related to the state report management which is currently titled "CyberKit4SME". As these endpoints are, by design, generic, they should not have the project name associated with them. Please find another name, such as "State Report Management" if that's appropriate.

The individual method descriptions need reviewing and revising as some of them are out of date. They should not be mentioning specific external integrations such as "Keenai" as the methods are generic.

### PR DESCRIPTION
**Pull request by panositi**
References and path names renamed from Cyberkit4SME to State Report Management now.

### CODE REVIEW

**Review by scp93ch — CHANGES_REQUESTED** [review]
It seems that it needs to be a little more nuanced than just renaming from Cyberkit4SME to State Report Management. I mean, very few of those methods or files is related to state report management. There's:

- Attack graph plotting
- Task management
- OpenVAS report processing
- Recommendations
- maybe more?

It's all been bundled under "Cyberkit4SME" and is now bundled under "State report management". The different code and endpoints should be separated bby funcctionality.

Can you make a proposal of what you think please?

**Comment by panositi** [comment]
Both `SSM Utils` and `State Report Management` should be regrouped to:

- SSM Utils: mainly utility methods generic
   - force adaptor lock remove
   - check model exists
   - validate model
   - jobs (check job status)
- State Report Management
   - states (get/post/delete)
   - process
   - download
   - delete report
- Notifications 
   - notify openvas report
- Recommendations
   - recommendations
   - download
- Plotting
   - path- plot
- Risk
   - calc-risk 

Also restore/clear/delete vulnerabilities endpoints should be removed as they cannot be used within the state report management cycle.

AdaptationCordinator should become a Notification endpoint

SIEA group should be absorbed or be wrappers to Notifications/State Report Management calls.

**Comment by scp93ch** [comment]
> Both `SSM Utils` and `State Report Management` should be regrouped to:
> 
> * SSM Utils: mainly utility methods generic
>   
>   * force adaptor lock remove
>   * check model exists
>   * validate model
>   * jobs (check job status)
> * State Report Management
>   
>   * states (get/post/delete)
>   * process
>   * download
>   * delete report
> * Notifications
>   
>   * notify openvas report
> * Recommendations
>   
>   * recommendations
>   * download
> * Plotting
>   
>   * path- plot
> * Risk
>   
>   * calc-risk
> 
> Also restore/clear/delete vulnerabilities endpoints should be removed as they cannot be used within the state report management cycle.
> 
> AdaptationCordinator should become a Notification endpoint
> 
> SIEA group should be absorbed or be wrappers to Notifications/State Report Management calls.

The grouping looks sensible, thanks. I don't know what the "vulnerabilities endpoints" are. Can we just do the re-grouping here and review other changes separately?

**Comment by panositi** [comment]
We can add another group e.g. `Vulnerabilities Management` but that will be confusing. 

Normally changes to TWAs for example are recorded and can be reversed by the adaptor. The calls in that group can show the list of the applied TWA changes, that list of changes is cached in the adaptor and can be revoked, or deleted from the cache.

All these calls are related with a `workflow` execution which the group of `state report management` handles better. I will group them separetely then.

**Review by scp93ch — APPROVED** [review]
The groups look sensible now, and mention of Keenai is removed. It's worth merging in. At some point we should rearrange the code as there is loads of stuff under the "state_report_management" folder that is nothing to do with it.

**Pull request merged**
